### ISSUE TITLE
Packages for .NET Core, and also the MiLight.Net package?

### ISSUE THREAD

**Issue by jskeet** [andy-scott/MiLight.Net#1]
Hi,

I'm looking to do some home automation with MiLight.Net... and it works fine, but using it from DNX is painful at the moment due to a lack of NuGet packages for .NET Core.

Any plans to publish these, and ideally the MiLight.Net package itself (rather than just the commands)?

**Comment by andy-scott** [comment]
Hi Jon,
  I will sort out a .Net Core package this weekend for the commands, I'll also take a look at packaging up the other code I have for sending the commands to the light controller.

Andy

**Comment by jskeet** [comment]
Cool. I've been playing around with this privately, and while `UdpClient` would make things much simpler, it appears not to be available in .NET Core. However, you can send reasonably simply anyway:

``` csharp
using (var socket = new Socket(AddressFamily.InterNetwork, SocketType.Dgram, ProtocolType.Udp))
{
    var serverAddr = IPAddress.Parse(this.ip);
    var endPoint = new IPEndPoint(serverAddr, this.port);
    var args = new SocketAsyncEventArgs { RemoteEndPoint = endPoint };
    args.SetBuffer(command, 0, command.Length);
    using (var done = new ManualResetEvent(false))
    {
        args.Completed += (sender, e) => done.Set();
        if (!socket.SendToAsync(args))
        {
            throw new Exception("Failed to send to lighting host"); // TODO: Better exception
        }
        if (!done.WaitOne(TimeSpan.FromSeconds(5)))
        {
            throw new Exception("Timed out sending to lighting host"); // TODO: Better exception
        }
    }
}
```

**Comment by andy-scott** [comment]
Hi Jon,
  I have pushed a pre-release version to nuget which supports .Net Core, let me know if you still have issues. I still need to add the controllers as packages.

Andy

**Comment by jskeet** [comment]
Wonderful, thanks. Have included the code above in my project and just referred to `MyLight.Net.Commands` and it's fine.
Will close this issue as it's no longer blocking for me - whether you create a new issue for the controllers is up to you, of course :)
